{% set version = "1.8.5" %}

package:
  name: libspatialindex
  version: {{ version }}

source:
  url: http://download.osgeo.org/libspatialindex/spatialindex-src-{{ version }}.tar.gz
  sha256: 7caa46a2cb9b40960f7bc82c3de60fa14f8f3e000b02561b36cbf2cfe6a9bfef
  patches:
    - tool.h.patch  # [win and vc>=14]
    - cmakelists.patch  # [win and vc>=14]

build:
  number: 4

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake  # [win]

test:
  commands:
    - test -f ${PREFIX}/lib/libspatialindex_c${SHLIB_EXT}  # [not win]

about:
  home: http://libspatialindex.github.io
  license: MIT
  license_file: COPYING
  summary: 'Extensible framework for robust spatial indexing'

extra:
  recipe-maintainers:
    - ocefpaf
