{% set version = "1.9.3" %}

package:
  name: libspatialindex
  version: {{ version }}

source:
  url: https://github.com/libspatialindex/libspatialindex/archive/{{ version }}.tar.gz
  sha256: 7b44340a3edc55c11abfc453bb60f148b29f569cef9e1148583e76132e9c7379

build:
  number: 0
  skip: True  # [win and vc<14]
  run_exports:
    # https://github.com/conda-forge/libspatialindex-feedstock/pull/18#issuecomment-473935733
    - {{ pin_subpackage('libspatialindex', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja  # [win]

test:
  commands:
    - test -f ${PREFIX}/lib/libspatialindex_c${SHLIB_EXT}  # [not win]

about:
  home: http://libspatialindex.github.io
  license: MIT
  license_file: COPYING
  summary: 'Extensible framework for robust spatial indexing'

extra:
  recipe-maintainers:
    - ocefpaf
