appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: r6XuwVlACBx+mk57WRlzwTlkKRY9c/CJUDYW/rVDrcDE3IsD8pATMcm+m85OIUYZ3n8gdLFnqRO1xV6ROsoiqvsdmnX+1ooUyVEB8wIAoSjqkYlDCpTsunVbI/tZSXh6IaryuxlO+aaSPqGSh8qnXFsi59efBrgrRYTffEjQ7dbAccHVqO9O/paqa783tN1UP9HmjDaOPIczMjobnN91hkSn8vUIirl1H/d/2n3qdp6w7YYcxCO3GeN0bxgskBmq7LtBJmOUJaViOCAh+U+6+WnWbjs7GYvdIbZdrMtUEiZozSEhbnKukAEPAUh5ZXdgMjR6gfVOnTjov4Rd2Yb+xEBBnyAyEcDgX23LovnbnogWe9Y0z1n/iMqmSOnPxf/j/TbDBhWVozcpZc0O5eFL0dFWNhCK3edFefKa8n9DLjFfK8eh1FzSof37pyttp0eC/4/9L3ekVtnny8S+3GWeMDlHCYUtTPmmvH2BYqfISfSbgGRtRC7szDup5sjcJn5Ten4TyEtJCN+TbhKXXDINJNk2ztG0SPlDKtUDx//YgCBgjRhj3V39A69V0tmwg/d+NheBFDT7Og4SloTrZFANbGatQfUk0b3knjGUyfdVgiyw2BmO30gZTbTurnNJdGWvl6138g+Tshq1jA9EaTgET8cvi7QrgtcCU0e3BWgk1F8=}
conda_forge_output_validation: true
